from typing import List
from dotenv import dotenv_values

config = dotenv_values(".env")

POSTGRES_USERNAME = config["POSTGRES_USERNAME"]
POSTGRES_PASSWORD = config["POSTGRES_PASSWORD"]
POSTGRES_HOST = config["POSTGRES_HOST"]
POSTGRES_PORT = config["POSTGRES_PORT"]
POSTGRES_NAME = config["POSTGRES_NAME"]
POSTGRES_URL = f"postgresql+asyncpg://{POSTGRES_USERNAME}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_NAME}"


REDIS_USERNAME = config["REDIS_USERNAME"]
REDIS_PASSWORD = config["REDIS_PASSWORD"]
REDIS_HOST = config["REDIS_HOST"]
REDIS_PORT = config["REDIS_PORT"]
REDIS_DB = config.get("REDIS_DB", "0")

REDIS_URL = f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

